/**
 * The `<home>` layout of docs/extension-less-onboarding.md §3.2: a per-user, version-stable
 * install directory deliberately kept outside the `M365AgentWorkspace` app-data root (§4.2) --
 * `initializeLocalState` never re-ACLs existing children of that root, so "install location" and
 * "application data location" must stay two different concerns.
 *
 * ```
 * <home>/
 *   bin/node | bin/node.exe   bundled runtime, copied; replaced by rename-swap on upgrade
 *   bin/apl.js                launcher regenerated by every install; imports app/<version>/dist/cli/index.js
 *   bin/apl | bin/apl.cmd     human shim for later commands; never spawned by hosts
 *   app/<version>/            the package; older versions kept for `self use` until `self prune`
 *   install.json              the single source of truth every entry point reads first (§4.7 C1)
 * ```
 *
 * Every function here is pure over its injected inputs (`env`/`platform`/`homedir`/`exec`) so the
 * Windows-only branches (the `node.exe.old` retention dance, the elevation check) can be exercised
 * from `tests/services/install-home.test.ts` running on macOS.
 */
import { randomBytes } from "node:crypto";
import { execFile } from "node:child_process";
import { promises as fs } from "node:fs";
import path from "node:path";
import { promisify } from "node:util";
import { z } from "zod";
import { DomainError } from "../domain/errors.js";
import { atomicWrite, readText } from "../config/storage.js";

const execFileAsync = promisify(execFile);

function pathModuleFor(platform: NodeJS.Platform): path.PlatformPath {
  return platform === "win32" ? path.win32 : path.posix;
}

/* ------------------------------------------------------------------------- resolveInstallHome */

export type InstallHomeOptions = {
  env: NodeJS.ProcessEnv;
  platform: NodeJS.Platform;
  homedir: string;
  /** `--home <dir>`, when the caller passed one. */
  override?: string;
};

/** override > `M365_AGENT_INSTALL_ROOT` > `%LOCALAPPDATA%\AgentPickLink` (win32) >
 * `~/.local/share/AgentPickLink` (§3.2). Never a roaming or folder-redirected profile.
 * `--home <dir>` and `M365_AGENT_INSTALL_ROOT` are resolved against the current working directory
 * (P1-11) so a relative value given on the command line (or in the environment) does not silently
 * turn into a path relative to whatever directory a later `fs` call happens to run from. */
export function resolveInstallHome(opts: InstallHomeOptions): string {
  if (opts.override) return path.resolve(opts.override);
  if (opts.env.M365_AGENT_INSTALL_ROOT) return path.resolve(opts.env.M365_AGENT_INSTALL_ROOT);
  const join = pathModuleFor(opts.platform).join;
  if (opts.platform === "win32") {
    const localAppData = opts.env.LOCALAPPDATA ?? join(opts.homedir, "AppData", "Local");
    return join(localAppData, "AgentPickLink");
  }
  return join(opts.homedir, ".local", "share", "AgentPickLink");
}

/** §4.7 C9: the same `%LOCALAPPDATA%`/home-directory prefixes `resolveInstallHome` itself derives
 * `<home>` from, handed to `src/services/integrations.ts`'s `IntegrationContext.variables` so a
 * workspace-file writer can recognize when a definition's `command`/`args` are home-based and
 * substitute the matching host variable. Deliberately independent of whether `<home>` actually
 * ended up under one of these prefixes (a `--home`/`M365_AGENT_INSTALL_ROOT` override moves `<home>`
 * elsewhere, in which case neither prefix ever matches and no substitution happens) -- this
 * function only ever reports what the prefixes *would be* on this machine, never `M365_AGENT_
 * INSTALL_ROOT` itself, which is the one input §4.7 C9 says must never drive a written file (a
 * GUI-launched host does not inherit shell exports). */
export function integrationVariablesFor(opts: Pick<InstallHomeOptions, "env" | "platform" | "homedir">): {
  localAppData?: string;
  userHome?: string;
} {
  const userHome = opts.homedir;
  if (opts.platform === "win32") {
    const localAppData =
      opts.env.LOCALAPPDATA ?? pathModuleFor(opts.platform).join(opts.homedir, "AppData", "Local");
    return { localAppData, userHome };
  }
  return { userHome };
}

/* ------------------------------------------------------------------------------ install.json */

export const InstallJsonSchema = z
  .object({
    version: z.string().min(1),
    installedBy: z.enum(["archive", "vsix", "source"]),
    runtime: z
      .object({
        path: z.string().min(1),
        source: z.enum(["bundled", "node", "electron"]),
        nodeVersion: z.string().min(1).optional()
      })
      .strict(),
    identity: z
      .object({
        command: z.string().min(1),
        args: z.array(z.string())
      })
      .strict(),
    clients: z.array(z.string()),
    workspaces: z.array(z.string()),
    platform: z.string().min(1),
    updatedAt: z.string().datetime()
  })
  .strict();

export type InstallJson = z.infer<typeof InstallJsonSchema>;

function installJsonPath(home: string): string {
  return path.join(home, "install.json");
}

/** `undefined` when `install.json` does not exist; throws (`SyntaxError` or `z.ZodError`) when it
 * exists but is not valid JSON matching `InstallJsonSchema` -- callers decide what "invalid" means
 * for them, the same convention `src/broker/broker-descriptor.ts` avoids only because a corrupt
 * descriptor is expected to self-heal by being overwritten; a corrupt `install.json` is not. */
export async function readInstallJson(home: string): Promise<InstallJson | undefined> {
  const text = await readText(installJsonPath(home));
  if (text === undefined) return undefined;
  return InstallJsonSchema.parse(JSON.parse(text));
}

export async function writeInstallJson(home: string, data: InstallJson): Promise<void> {
  const validated = InstallJsonSchema.parse(data);
  await atomicWrite(installJsonPath(home), `${JSON.stringify(validated, null, 2)}\n`);
}

/* --------------------------------------------------------------------------------- file copies */

async function pathExists(target: string): Promise<boolean> {
  try {
    await fs.access(target);
    return true;
  } catch {
    return false;
  }
}

/** Recursively copies `source` to `destination`, explicitly preserving each file's permission
 * bits (in particular the executable bit) rather than relying on `fs.cp`'s undocumented
 * behaviour. Symbolic links are recreated as links, never followed. */
async function copyTree(source: string, destination: string): Promise<void> {
  await fs.mkdir(destination, { recursive: true });
  const entries = await fs.readdir(source, { withFileTypes: true });
  for (const entry of entries) {
    const from = path.join(source, entry.name);
    const to = path.join(destination, entry.name);
    if (entry.isSymbolicLink()) {
      // Never recreate the link itself: `fs.symlink` fails with EPERM on Windows without
      // Developer Mode enabled. Copy whatever the link resolves to instead -- npm's
      // `node_modules/.bin` shims are the common case -- and skip a broken (dangling) link
      // rather than failing the whole staging pass over a file nothing here ever runs.
      let stat;
      try {
        stat = await fs.stat(from);
      } catch {
        continue;
      }
      if (stat.isDirectory()) {
        await copyTree(from, to);
      } else {
        await fs.copyFile(from, to);
        await fs.chmod(to, stat.mode);
      }
      continue;
    }
    if (entry.isDirectory()) {
      await copyTree(from, to);
      continue;
    }
    await fs.copyFile(from, to);
    const stat = await fs.stat(from);
    await fs.chmod(to, stat.mode);
  }
}

/** Stages `source` at `home/app/<version>.tmp-<random>` then swaps it in as `home/app/<version>`,
 * replacing an existing copy atomically (rename old aside, rename new in, delete old aside). */
async function replaceDirectoryAtomically(temporary: string, target: string): Promise<void> {
  if (!(await pathExists(target))) {
    await fs.rename(temporary, target);
    return;
  }
  const aside = `${target}.old-${randomBytes(6).toString("hex")}`;
  await fs.rename(target, aside);
  try {
    await fs.rename(temporary, target);
  } catch (error) {
    // Best-effort restore so a failed swap does not leave the version directory missing.
    await fs.rename(aside, target).catch(() => undefined);
    throw error;
  }
  await fs.rm(aside, { recursive: true, force: true });
}

export type StageVersionOptions = {
  sourceDir: string;
  home: string;
  version: string;
};

/** Copies `sourceDir` to `app/<version>`, exec bits preserved, replacing any existing directory
 * for that version atomically. Returns the final `app/<version>` path. */
export async function stageVersion(opts: StageVersionOptions): Promise<string> {
  const appDir = path.join(opts.home, "app");
  await fs.mkdir(appDir, { recursive: true });
  const temporary = path.join(appDir, `${opts.version}.tmp-${randomBytes(6).toString("hex")}`);
  await copyTree(opts.sourceDir, temporary);
  const target = path.join(appDir, opts.version);
  await replaceDirectoryAtomically(temporary, target);
  return target;
}

/* -------------------------------------------------------------------------------- installRuntime */

export type InstallRuntimeOptions = {
  nodeBinary: string;
  home: string;
  platform: NodeJS.Platform;
  /** Runs an external command; injectable so `xattr` (quarantine removal, darwin only) never
   * actually executes in tests. Defaults to a real `execFile`. */
  exec?: (command: string, args: string[]) => Promise<{ stdout: string }>;
  /** Injectable seam for the final rename-in step below, so a test can force that specific
   * failure (a real filesystem cannot reliably reproduce "the rename-aside above already
   * succeeded, but the final rename still fails" without an actual OS-level lock). Defaults to
   * `fs.rename`. */
  rename?: (from: string, to: string) => Promise<void>;
};

const defaultExec = async (command: string, args: string[]): Promise<{ stdout: string }> =>
  execFileAsync(command, args, { windowsHide: true, timeout: 15_000 });

/** Copies `nodeBinary` to `bin/node` (`bin/node.exe` on win32) via rename-swap. On win32, an
 * existing target is renamed to `node.exe.old` first (a running broker may still hold the file
 * open) and a previous `.old` is deleted best-effort; POSIX overwrites in place because renaming
 * over an open file is safe there. On darwin, the quarantine attribute is removed best-effort from
 * the copied binary only (never from anything else). */
export async function installRuntime(opts: InstallRuntimeOptions): Promise<string> {
  const exec = opts.exec ?? defaultExec;
  const rename = opts.rename ?? ((from: string, to: string) => fs.rename(from, to));
  // Real disk I/O always uses the host's own native path module: `home` is a location on *this*
  // machine, and in production `opts.platform` always equals `process.platform` anyway. Only the
  // filename ("node" vs "node.exe") and the behavioural branches below vary with `platform` --
  // that is what lets tests exercise the win32-only dance from a real macOS/Linux filesystem.
  const binDir = path.join(opts.home, "bin");
  await fs.mkdir(binDir, { recursive: true });
  const nodeName = opts.platform === "win32" ? "node.exe" : "node";
  const target = path.join(binDir, nodeName);
  const temporary = path.join(binDir, `.${nodeName}.tmp-${randomBytes(6).toString("hex")}`);

  await fs.copyFile(opts.nodeBinary, temporary);
  const stat = await fs.stat(opts.nodeBinary);
  await fs.chmod(temporary, stat.mode | 0o111);

  if (opts.platform === "win32") {
    const oldPath = path.join(binDir, "node.exe.old");
    await fs.rm(oldPath, { force: true }).catch(() => undefined);
    if (await pathExists(target)) {
      try {
        await fs.rename(target, oldPath);
      } catch {
        // Either the delete above or this rename-aside failed -- most likely a running broker
        // still holds the previous node.exe.old or node.exe open. Fall back to a uniquely named
        // aside rather than leaving the live binary in place, which would make the rename below
        // fail with a confusing "destination exists" error instead of installing the new runtime.
        const fallbackOld = path.join(binDir, `node.exe.old-${randomBytes(6).toString("hex")}`);
        await fs.rename(target, fallbackOld);
      }
    }
  }
  try {
    await rename(temporary, target);
  } catch (error) {
    throw new Error(
      `Could not install the AgentPickLink runtime at ${target}: ` +
        (error instanceof Error ? error.message : String(error)),
      { cause: error }
    );
  }

  if (opts.platform === "darwin") {
    await exec("xattr", ["-d", "com.apple.quarantine", target]).catch(() => undefined);
  }
  return target;
}

/* --------------------------------------------------------------------------------- launchers */

/** `devEntry`, when given, is an absolute path to a source checkout's `dist/cli/index.js` (§4.7
 * C2 `install --dev`): `bin/apl.js` imports it directly, verbatim, instead of building
 * `app/<version>/dist/cli/index.js` -- there is no `app/<version>` at all in that mode, since
 * nothing is staged. */
function renderAplJs(version: string, devEntry?: string): string {
  const entryLine = devEntry
    ? `const entry = ${JSON.stringify(devEntry)};`
    : `const entry = path.join(__dirname, "..", "app", ${JSON.stringify(version)}, "dist", "cli", "index.js");`;
  return [
    "#!/usr/bin/env node",
    '"use strict";',
    "// Regenerated by every install/self-use (src/services/install-home.ts writeLaunchers).",
    "// This file is always CommonJS (no ancestor package.json under <home>), so a dynamic",
    "// import() -- valid in CommonJS -- is used to load the ESM CLI entry point.",
    'const path = require("node:path");',
    'const { pathToFileURL } = require("node:url");',
    "",
    entryLine,
    "",
    "import(pathToFileURL(entry).href)",
    "  .then((mod) => mod.runCli(process.argv))",
    "  .catch((error) => {",
    "    process.stderr.write(`${error instanceof Error ? error.message : String(error)}\\n`);",
    "    process.exitCode = 1;",
    "  });",
    ""
  ].join("\n");
}

const POSIX_SHIM = [
  "#!/bin/sh",
  'DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)',
  'exec "$DIR/node" "$DIR/apl.js" "$@"',
  ""
].join("\n");

const WINDOWS_SHIM = ["@echo off", '"%~dp0node.exe" "%~dp0apl.js" %*', ""].join("\r\n");

export type WriteLaunchersOptions = {
  home: string;
  version: string;
  platform: NodeJS.Platform;
  /** §4.7 C2 `install --dev`: an absolute path to a source checkout's `dist/cli/index.js`, used
   * verbatim by the generated `bin/apl.js` instead of `app/<version>/dist/cli/index.js`. */
  devEntry?: string;
  /** Electron stays at its original application location; it must never be copied. */
  electronBinary?: string;
};

/** Regenerates `bin/apl.js` (every install and every `self use`) and, matching the current
 * platform, the human shim `bin/apl` (POSIX) or `bin/apl.cmd` (Windows, CRLF). Hosts spawn
 * `bin/node`/`bin/apl.js` directly; the shims are for humans running later commands and must never
 * be spawned from code. */
export async function writeLaunchers(opts: WriteLaunchersOptions): Promise<void> {
  // See installRuntime's comment: real disk I/O uses the host's native path module regardless of
  // the declared `platform`, which only selects which shim/behaviour to write.
  const binDir = path.join(opts.home, "bin");
  await fs.mkdir(binDir, { recursive: true });

  const aplJsPath = path.join(binDir, "apl.js");
  await fs.writeFile(aplJsPath, renderAplJs(opts.version, opts.devEntry), "utf8");
  // §P1-7: a one-line sidecar naming the version `bin/apl.js` actually imports right now --
  // `self prune`/`self use`/`self status` read this (falling back to `install.json` when it is
  // missing, e.g. an install staged before this sidecar existed) instead of trusting
  // `install.json.version` alone, which can disagree with `bin/apl.js` if the two are ever
  // updated out of step.
  await fs.writeFile(path.join(binDir, "current-version"), `${opts.version}\n`, "utf8");

  if (opts.platform === "win32") {
    if (opts.electronBinary && /[%"\r\n]/.test(opts.electronBinary))
      throw new DomainError(
        "INVALID_ARGUMENT",
        "The Electron path cannot be represented safely in a cmd launcher."
      );
    const shim = opts.electronBinary
      ? [
          "@echo off",
          "setlocal",
          'set "ELECTRON_RUN_AS_NODE=1"',
          `"${opts.electronBinary}" "%~dp0apl.js" %*`,
          ""
        ].join("\r\n")
      : WINDOWS_SHIM;
    await fs.writeFile(path.join(binDir, "apl.cmd"), shim, "utf8");
  } else {
    const shPath = path.join(binDir, "apl");
    const quoted = opts.electronBinary
      ? "'" + opts.electronBinary.replaceAll("'", "'\"'\"'") + "'"
      : undefined;
    const shim = quoted
      ? POSIX_SHIM.replace('exec "$DIR/node"', `ELECTRON_RUN_AS_NODE=1 exec ${quoted}`)
      : POSIX_SHIM;
    await fs.writeFile(shPath, shim, { encoding: "utf8", mode: 0o755 });
    await fs.chmod(shPath, 0o755);
    await fs.chmod(aplJsPath, 0o755);
  }
}

/** §P1-7: the version `bin/apl.js` actually imports, per the `bin/current-version` sidecar
 * `writeLaunchers` writes next to it -- falling back to `installJson.version` when the sidecar is
 * absent (an install staged before this sidecar existed). Returns `undefined` when neither is
 * available. */
export async function readCurrentVersion(home: string): Promise<string | undefined> {
  const text = await readText(path.join(home, "bin", "current-version"));
  const trimmed = text?.trim();
  return trimmed && trimmed.length > 0 ? trimmed : undefined;
}

/** The sidecar wins over `installJson?.version` whenever both are available -- see
 * `readCurrentVersion`'s doc comment. Used by `self prune`/`self use`/`self status` so all three
 * agree with `bin/apl.js` even when `install.json` itself has drifted. */
export async function currentVersion(
  home: string,
  installJson?: Pick<InstallJson, "version">
): Promise<string | undefined> {
  return (await readCurrentVersion(home)) ?? installJson?.version;
}

/* ------------------------------------------------------------------------------------ identity */

export type IdentityOptions = { home: string; platform: NodeJS.Platform };

/** The identity every client file gets (§3.2): `command` + the args prefix. Never changes across
 * versions -- `bin/apl.js` is what changes on upgrade, not this path. */
export function identityFor(opts: IdentityOptions): { command: string; args: string[] } {
  const join = pathModuleFor(opts.platform).join;
  const nodeName = opts.platform === "win32" ? "node.exe" : "node";
  return {
    command: join(opts.home, "bin", nodeName),
    args: [join(opts.home, "bin", "apl.js"), "serve"]
  };
}

/* --------------------------------------------------------------------------- version management */

/** Sorts `x.y.z` version directory names newest first; unparseable names sort last. */
function compareVersionsDescending(left: string, right: string): number {
  const parse = (value: string): number[] => {
    const match = /^v?(\d+)\.(\d+)\.(\d+)/.exec(value);
    return match ? [Number(match[1]), Number(match[2]), Number(match[3])] : [-1, -1, -1];
  };
  const a = parse(left);
  const b = parse(right);
  for (let index = 0; index < 3; index += 1) if (a[index] !== b[index]) return b[index] - a[index];
  return 0;
}

/** Lists installed versions (`app/<version>` directories), newest first. A missing `app/`
 * directory (nothing installed yet) yields an empty list rather than throwing. */
export async function listVersions(home: string): Promise<string[]> {
  let entries;
  try {
    entries = await fs.readdir(path.join(home, "app"), { withFileTypes: true });
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") return [];
    throw error;
  }
  return entries
    .filter((entry) => entry.isDirectory() && !entry.name.includes(".tmp-"))
    .map((entry) => entry.name)
    .sort(compareVersionsDescending);
}

export type UseVersionOptions = { home: string; version: string; platform: NodeJS.Platform };

/** Re-points `bin/apl.js` at an already-staged version. Refuses when `app/<version>` is missing --
 * `self use` must never point the launcher at a version that cannot run. */
/** Directory-name-safe version strings only: `opts.version` ends up as a path segment
 * (`app/<version>`) and, unvalidated, could otherwise be used to traverse outside `<home>` (e.g.
 * `../../etc`) or collide with a reserved name. */
const VALID_VERSION = /^[A-Za-z0-9._+-]+$/;

export async function useVersion(opts: UseVersionOptions): Promise<void> {
  if (!VALID_VERSION.test(opts.version))
    throw new DomainError("INVALID_ARGUMENT", `Invalid version: ${opts.version}`, false, {
      remediation: "Use a version listed by `self status` (letters, digits, '.', '_', '+', '-' only)."
    });
  const versionDir = path.join(opts.home, "app", opts.version);
  if (!(await pathExists(versionDir)))
    throw new DomainError(
      "INVALID_ARGUMENT",
      `AgentPickLink ${opts.version} is not installed under ${opts.home}.`,
      false,
      { remediation: "Run apl-setup (or self install) for that version before switching to it." }
    );
  const installed = await readInstallJson(opts.home);
  await writeLaunchers({
    ...opts,
    ...(installed?.runtime.source === "electron" ? { electronBinary: installed.runtime.path } : {})
  });
}

export type PruneVersionsOptions = { home: string; keep: string };

/** Deletes every `app/<version>` other than `keep`. Returns the versions removed. */
export async function pruneVersions(opts: PruneVersionsOptions): Promise<string[]> {
  const removed: string[] = [];
  for (const version of await listVersions(opts.home)) {
    if (version === opts.keep) continue;
    await fs.rm(path.join(opts.home, "app", version), { recursive: true, force: true });
    removed.push(version);
  }
  return removed;
}

/* ------------------------------------------------------------------------------------ elevation */

export type AssertNotElevatedOptions = {
  platform?: NodeJS.Platform;
  /** Runs `whoami /groups`; injectable so no real elevation probe runs in tests. */
  exec?: (command: string, args: string[]) => Promise<{ stdout: string }>;
  /** Returns the current POSIX uid, or `undefined` when unavailable (e.g. injected for win32 tests). */
  getuid?: () => number | undefined;
};

/** §4.7 C11: `install` refuses to run elevated, because it would land in the administrator's
 * profile rather than the invoking user's. win32: the current token carries the High Mandatory
 * Level SID (`S-1-16-12288`) when running elevated (`whoami /groups`). POSIX: uid 0. A failure to
 * even run the probe is not itself treated as elevation -- it fails open rather than blocking a
 * legitimate install because `whoami` could not be found. */
export async function assertNotElevated(opts: AssertNotElevatedOptions = {}): Promise<void> {
  const platform = opts.platform ?? process.platform;
  const exec = opts.exec ?? defaultExec;
  const getuid = opts.getuid ?? (() => process.getuid?.());

  if (platform === "win32") {
    let stdout: string;
    try {
      ({ stdout } = await exec("whoami", ["/groups"]));
    } catch {
      return;
    }
    if (stdout.includes("S-1-16-12288"))
      throw new DomainError(
        "POLICY_BLOCKED",
        "AgentPickLink cannot be installed from an elevated (Run as administrator) prompt.",
        false,
        {
          remediation:
            "Close this elevated prompt and re-run apl-setup from a normal, non-administrator prompt."
        }
      );
    return;
  }

  if (getuid() === 0)
    throw new DomainError("POLICY_BLOCKED", "AgentPickLink cannot be installed as root.", false, {
      remediation: "Re-run apl-setup as your own (non-root) user."
    });
}

/* -------------------------------------------------------------------------------- build stamp */

/** §4.7 C14's `M365_AGENT_BUILD` value: `<version>` alone, or `<version>+<build>` when a build
 * identifier is given. Written into workspace-file entries only -- the cache-buster VS Code needs
 * to notice a version-independent identity has actually changed. */
export function buildStamp(version: string, build?: string): string {
  return build ? `${version}+${build}` : version;
}
