/** Guidance to the calling AI, not a silent rewrite of a user's message or an agent definition. */
export const FILE_GENERATION_INSTRUCTIONS = `For file-generation requests, include the relevant portability requirements below in the message to the Microsoft 365 agent, while preserving the user's language, content, filenames, and requested format. Do not silently substitute an English-only or different-format deliverable.
- PDF: use fonts that cover every requested character, including Japanese/CJK in body text, tables, charts, headers and footers. Embed the required fonts in the PDF; a font available only on the generating machine is insufficient. Render every page and check missing glyphs, black squares, clipping and layout; check text extraction too. Extraction alone does not prove correct rendering on Windows.
- DOCX, XLSX and PPTX: preserve Unicode text; use fonts with the needed language coverage available in the target application, or embed fonts where the format, generator and font license allow it. Reopen the actual output and verify text, tables, formula references/results, charts and slide layout as applicable. Do not replace formulas with text or claim cross-platform rendering without testing it.
- CSV, TSV, TXT, JSON, XML and HTML: specify the encoding and preserve Unicode. Prefer UTF-8; for CSV intended for direct opening in Windows Excel, request UTF-8 with BOM unless the user's format requirements say otherwise. Preserve delimiters, quoting, newlines and declared encodings. Do not add a BOM indiscriminately to other formats.
- SVG and images: check rendered non-Latin labels; SVG fonts must be portable or converted to paths when appropriate. For audio/video and other formats, reopen with an appropriate reader and check the requested content rather than only the extension.
- ZIP and other archives: verify integrity, Unicode filenames, the expected entry list and the contents of each extracted file. Do not run extracted executables, scripts or macros as validation.
Ask the generator to report checks it could not perform and generation limitations instead of claiming success. After receiving files, read the saved resources and validate the relevant content with available tools before telling the user they are correct. For every file format, first check for a compatible reader, renderer or player in the calling environment; a missing tool or extension alone does not mean that the file is corrupt or in the wrong format. Use the attachment MIME and filename together. AgentPickLink does not bundle document readers, spreadsheet engines, renderers or media players for the calling environment. For PDFs, first check for an available PDF reader/text extractor and page renderer in the calling environment. Use the returned localPath or resource_link; if reading via MCP resources/read, decode its base64 blob to the original bytes before passing it to a PDF tool. A missing filename extension does not mean the file is not a PDF: consult its MIME type and PDF header. Prefer a proper PDF parser over ad hoc stream decompression, which can miss font mappings, encodings and page content. AgentPickLink saves files and does not supply a PDF reader or renderer to the calling environment. If a reader or renderer is unavailable, report text-extraction and visual-verification limitations separately; do not claim an unreadable or corrupt file solely because a tool is missing. A saved status or matching SHA-256 proves transfer integrity, not fonts, rendering, formulas, or semantic correctness. Distinguish checks you performed from generator claims; report unavailable validation explicitly. Never repair source content by guessing missing characters, overwrite the original attachment, execute active content, or automatically resend an uncertain or failed request. Any regeneration must be a deliberate new request.`;

export const FILE_GENERATION_TOOL_HINT =
  " For generated files, request portable Japanese/CJK fonts (embedded in PDFs), preserved Unicode/encoding, and format-specific reopen/render checks. Read and check the actual files before reporting content quality; saved means transferred, not validated. Follow the server's file-generation instructions.";
